{
    "__default__" : {
        "job-name"       : "sm.{rule}",
        "partition"      : "agap_long", 
        "ntasks"         : 1,
        "cpus-per-task"  : 4,
        "mem-per-cpu"    : 4G,
        "output"         : "logs/%j.%N.out.txt",
        "error"          : "logs/%j.%N.err.txt"
    }
}
