blast_databases:
  SwissProt : "/lustre/agap/BANK/uniprot/uniprot-swissprot_33090_20210313.fasta"
  TrEMBL: "/nfs/work/agap/BANK/uniprot/uniprot-trembl_33090_20210313.fasta"  

blast_repeat_database:
  repbase: "db/repbase23.12_aaSeq_cleaned_2020.fa"

hmm_databases:
  Retro_gag: "db/Retrotran_gag_3.hmm"
  retro_gypsy: "db/Transposase_28_Gypsy.hmm"

input_proteome:
  "DJ123": "/lustre/sorianoa/eugene_annotation_rice_new/output_egnep_2/DJ123/DJ123_prot.fna"

input_gff3:
  "DJ123": "/lustre/sorianoa/eugene_annotation_rice_new/output_egnep_2/DJ123/DJ123.gff3"

input_genomes:
  "DJ123": "/lustre/sorianoa/eugene_annotation_rice_new/output_egnep_2/DJ123/DJ123"

#Should be DL from https://busco-data.ezlab.org/v5/data/lineages/ and uncompress    
busco_path: "db/busco_downloads/"
lineage: "poales_odb10"
use_diamond: 1
only_reannotate: 0
tag: "ID"
keywork_to_remove:
  - "Retrotrans_gag"
  - "polyprotein"
  - "Gag.Pol"
  - "Gypsy"
  - "Copia"
  - "Reverse transcriptase"
  - "transpos"
  - "elomer"
  - "Elongation factor"
  - "EF-Ts"

#TODO : Double check this list with https://gitlab.southgreen.fr/hub/vaniseq/-/wikis/Gene-Filtering-VANPL_CR0040_3300M_all_ctg#ipr2-ipr018289-mule-transposase-domain-yes-but-ipr031052-no-far1-family-and-no-modules. This has been done.
ipro_term_to_remove:
  - "IPR000123"
  - "IPR015706"
  - "IPR013103"
  - "IPR003036"
  - "IPR002079"
  - "IPR004004"
  - "IPR003141"
  - "IPR005162"
  - "IPR000721"
  - "IPR014817"
  - "IPR014834"
  - "IPR016195"
  - "IPR015699"
  - "IPR004312"
  - "IPR001584"
  - "IPR004332"
  - "IPR004028"
  - "IPR004957"
  - "IPR003545"
  - "IPR018289"


fasta_split_number: 4

params:
  global_blast_threads: 14
  interproscan_threads: 14
  global_diamond_threads: 14
  busco_threads: 10 

modules:
  samtools: "samtools/1.14-bin"
  hmmer: "hmmer/3.3.2-bin"
  blast: "ncbi-blast/2.10.1+"
  interproscan: "interproscan/5.48-83.0"
  seqkit: "seqkit/2.0.0"
  diamond: "diamond/2.0.11"
  func_annot: "functional_annotation/1.0.0"
  gffread: "gffread/0.12.6"
  busco: "busco/5.0.0"
  R: "R/packages/4.1.0"
