
# Genome to be annotated (Assembly, GFF3 and corresponding protein fasta file)
# Same keys for a genome, can be multiple
#input_proteome:
#  "genomeA": "path_to_proteomeA"
#  "genomeB": "path_to_proteomeB"
#  "genomeX": "path_to_proteomeX"
  
#input_gff3:
#  "genomeA": "path_to_gffA"
#  "genomeB": "path_to_gffB"
#  "genomeX": "path_to_gffX"
  
#input_genomes:
#  "genomeA": "path_to_genomeA"
#  "genomeB": "path_to_genomeB"
#  "genomeX": "path_to_genomeX"
  
input_proteome:
  "DJ123": "/lustre/sorianoa/eugene_annotation_rice_new/output_egnep_2/DJ123/DJ123_prot.fna"

input_gff3:
  "DJ123": "/lustre/sorianoa/eugene_annotation_rice_new/output_egnep_2/DJ123/DJ123.gff3"

input_genomes:
  "DJ123": "/lustre/sorianoa/eugene_annotation_rice_new/output_egnep_2/DJ123/DJ123"

# Function transfer based on sequence similarity 
# The list is ordered according to the trust given to the database. 
# 
blast_databases:
  SwissProt : "/lustre/agap/BANK/uniprot/uniprot-swissprot_33090_20210313.fasta"
  TrEMBL: "/nfs/work/agap/BANK/uniprot/uniprot-trembl_33090_20210313.fasta"  


#Should be DL from https://busco-data.ezlab.org/v5/data/lineages/ and uncompress    
busco_path: "db/busco_downloads/"
lineage: "viridiplantae_odb10"

# Method for the protein similarity search (1 for diamond, 0 for blastp)
use_diamond: 1

# GFF3 Tag corresponding to sequence identifier (input_proteome)
# Allowed values are: ID, Name, locus_tag
# Require for GFF3 enrichment
tag: "ID"

# 0 Only perform functional annotation (BLAST/Diamond + InterProScan)
# 1 For filter and check annotation quality ( filter transposable element genes and doubtful genes), refer to https://gitlab.southgreen.fr/hub/vaniseq/-/wikis/Gene-Filtering-VANPL_CR0040_3300M_all_ctg
only_reannotate: 0

# 
blast_repeat_database:
  repbase: "db/repbase23.12_aaSeq_cleaned_2020.fa"

hmm_databases:
  Retro_gag: "db/Retrotran_gag_3.hmm"
  retro_gypsy: "db/Transposase_28_Gypsy.hmm"

keywork_to_remove:
  - "Retrotrans_gag"
  - "polyprotein"
  - "Gag.Pol"
  - "Gypsy"
  - "Copia"
  - "Reverse transcriptase"
  - "transpos"
  - "elomer"
  - "Elongation factor"
  - "EF-Ts"

ipro_term_to_remove:
  - "IPR000123"
  - "IPR015706"
  - "IPR013103"
  - "IPR003036"
  - "IPR002079"
  - "IPR004004"
  - "IPR003141"
  - "IPR005162"
  - "IPR000721"
  - "IPR014817"
  - "IPR014834"
  - "IPR016195"
  - "IPR015699"
  - "IPR004312"
  - "IPR001584"
  - "IPR004332"
  - "IPR004028"
  - "IPR004957"
  - "IPR003545"
  - "IPR018289"

# Split FASTA into 10 files (increase/decrease this value if need, 5000 sequence for each part is recommended) 
fasta_split_number: 10

# Threads
params:
  global_blast_threads: 14
  interproscan_threads: 14
  global_diamond_threads: 14
  busco_threads: 10 

# Use envmodules (muse-login01)
modules:
  samtools: "samtools/1.14-bin"
  hmmer: "hmmer/3.3.2-bin"
  blast: "ncbi-blast/2.10.1+"
  interproscan: "interproscan/5.48-83.0"
  seqkit: "seqkit/2.0.0"
  diamond: "diamond/2.0.11"
  func_annot: "functional_annotation/1.0.0"
  gffread: "gffread/0.12.6"
  busco: "busco/5.0.0"
  R: "R/packages/4.1.0"
